DATALOADER:
  TRAIN_SHUFFLE: False

MODEL:
  FREEZE2D: True
  EVAL: True
  WEIGHTS: "models/front3d.pth"
  MODEL2D:
    BACKBONE:
      NAME: "resnet50"
      DILATION: (False, False, False)
      PRETRAINED: True
    BOTTOM_UP:
      IN_FEATURE:
        FEATURE_KEY: "res5"
        IN_CHANNELS: 2048
        LOW_LEVEL_KEY: [ "res4", "res3", "res2" ]
        LOW_LEVEL_CHANNELS: (1024, 512, 256)

      SEMANTIC:
        ASPP:
          ATROUS_RATES: (3, 6, 9)
          LOW_LEVEL_CHANNELS_PROJECT: (128, 64, 32)
          ASPP_CHANNELS: 256
        DECODER:
          DECODER_CHANNELS: 256
        HEAD:
          HEAD_CHANNELS: 256
          NUM_CLASSES: (13,)
          CLASS_KEY: [ "semantic2d" ]

      INSTANCE:
        ASPP:
          ATROUS_RATES: (3, 6, 9)
          LOW_LEVEL_CHANNELS_PROJECT: (64, 32, 16)
          ASPP_CHANNELS: 256
        DECODER:
          DECODER_CHANNELS: 128
        HEAD:
          HEAD_CHANNELS: 32
          NUM_CLASSES: (1, 2)
          CLASS_KEY: ["center2d", "offset2d"]

      LOSS:
        SEMANTIC:
          NAME: 'CrossEntropyLoss'
          WEIGHT: 1.
          IGNORE: 255
        CENTER:
          NAME: 'MSELoss'
          WEIGHT: 200.
        OFFSET:
          NAME: 'L1Loss'
          WEIGHT: 0.01

    DEPTH:
      FEATURE_KEY: [ "res5", "res4", "res3", "res2" ]
      BLOCK_CHANNELS: (2048, 1024, 512, 256)
      FEATURE_CHANNELS: 64
      NUM_CLASSES: (100, 1)
      CLASS_KEY: ["occupancy2d", "depth"]
      LOSS:
        DEPTH:
          WEIGHT: 10.
        OCCUPANCY2D:
          NAME: 'BCELoss'
          WEIGHT: 0.1

  PROJECTION:
    TRUNCATION: 3.0
    VOXEL_SIZE: 0.03
    DEPTH_MIN: 0.4
    DEPTH_MAX: 6.0
    IMAGE_SIZE: (120, 160)
    GRID_DIMENSIONS: [256, 256, 256]

  MODEL3D:
    BACKBONE:
      NAME: "resnet18"
      DILATION: (False, False, False)
    BOTTOM_UP:
      IN_FEATURE:
        FEATURE_KEY: "res5"
        IN_CHANNELS: 256
        LOW_LEVEL_KEY: [ "res4", "res3", "res2" ]
        LOW_LEVEL_CHANNELS: (128, 64, 32)

      SEMANTIC:
        ASPP:
          ATROUS_RATES: (3, 6, 9)
          LOW_LEVEL_CHANNELS_PROJECT: (64, 32, 16)
          ASPP_CHANNELS: 64
        DECODER:
          DECODER_CHANNELS: 64
        HEAD:
          HEAD_CHANNELS: 64
          NUM_CLASSES: (13,)
          CLASS_KEY: [ "semantic3d" ]

      INSTANCE:
        ASPP:
          ATROUS_RATES: (3, 6, 9)
          LOW_LEVEL_CHANNELS_PROJECT: (64, 32, 16)
          ASPP_CHANNELS: 32
        DECODER:
          DECODER_CHANNELS: 32
        HEAD:
          HEAD_CHANNELS: 32
          NUM_CLASSES: (1, 3)
          CLASS_KEY: ["center3d", "offset3d"]

      GEOMETRY:
        ASPP:
          ATROUS_RATES: (3, 6, 9)
          LOW_LEVEL_CHANNELS_PROJECT: (64, 32, 16)
          ASPP_CHANNELS: 32
        DECODER:
          DECODER_CHANNELS: 32
        HEAD:
          HEAD_CHANNELS: 32
          NUM_CLASSES: (1, 1)
          CLASS_KEY: [ "occupancy3d", "geometry" ]

      LOSS:
        OCCUPANCY:
          NAME: 'BCELoss'
          WEIGHT: 10.
        SEMANTIC:
          NAME: 'CrossEntropyLoss'
          WEIGHT: 1.
          IGNORE: 255
        CENTER:
          NAME: 'MSELoss'
          WEIGHT: 200.
        OFFSET:
          NAME: 'L1Loss'
          WEIGHT: 0.01
        GEOMETRY:
          NAME: 'L1Loss'
          WEIGHT: 1.

  POST_PROCESSING:
    CENTER_THRESHOLD: 0.1
    NMS_KERNEL: 7
    TOP_K_INSTANCE: 200
    STUFF_AREA: 64


DATASET:
  ROOT: "datasets/front3d/"
  DATASET: "Front3D"
  FIELDS: ("color", "depth", "instance2d", "geometry", "instance3d", "semantic3d")
  FILE_LIST: "resources/front3d/validation_list.txt"
  # FILE_LIST: "resources/front3d/train_list.txt"
  IMAGE_SIZE: (240, 320)
  INTRINSIC: [ [ 277.1281435,   0.       , 159.5,  0. ],
               [ 0.       , 277.1281435, 119.5,  0. ],
               [ 0.       ,   0.       ,   1. ,  0. ],
               [ 0.       ,   0.       ,   0. ,  1. ] ]  # Fixed 3D-Front intrinsic

  NUM_CLASSES: 13
  STUFF_CLASSES: [0, 10, 11, 12]
  TRAIN_SPLIT: 'train'
  TEST_SPLIT: 'val'
  MIRROR: True
  MIN_SCALE: 0.5
  MAX_SCALE: 2.0
  SCALE_STEP_SIZE: 0.1
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  IGNORE_STUFF_IN_OFFSET: True
  SMALL_INSTANCE_AREA: 4096
  SMALL_INSTANCE_WEIGHT: 3
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0
  OPTIMIZER: "adam"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR" #"WarmupPolyLR"
  STEPS: (32000, 38000)
  WARMUP_ITERS: 0
TRAIN:
  MAX_ITER: 40000
  RESUME: False
IMS_PER_BATCH: 1
OUTPUT_DIR: "./output/front3d"
GPUS: (0,) # 1, 2, 3, 4, 5, 6, 7)
WORKERS: 16
CKPT_FREQ: 2500
PRINT_FREQ: 1